# Generated by Django 5.0 on 2024-01-03 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_cartitems_cart"),
        ("product", "0003_alter_product_color_variant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitems",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.product",
            ),
        ),
    ]
